
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE ID OPENptag : OPEN args CLOSEargs : IDargs : args ID'
    
_lr_action_items = {'OPEN':([0,],[2,]),'$end':([1,5,],[0,-1,]),'ID':([2,3,4,6,],[4,6,-2,-3,]),'CLOSE':([3,4,6,],[5,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ptag':([0,],[1,]),'args':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ptag","S'",1,None,None,None),
  ('ptag -> OPEN args CLOSE','ptag',3,'p_ptag','parser.py',5),
  ('args -> ID','args',1,'p_args','parser.py',10),
  ('args -> args ID','args',2,'p_args_multiple','parser.py',14),
]
