
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALT END ID INV OPEN SRC\n    html_tag : OPEN SRC ALT args END \n    args : IDargs : args ID'
    
_lr_action_items = {'OPEN':([0,],[2,]),'$end':([1,7,],[0,-1,]),'SRC':([2,],[3,]),'ALT':([3,],[4,]),'ID':([4,5,6,8,],[6,8,-2,-3,]),'END':([5,6,8,],[7,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html_tag':([0,],[1,]),'args':([4,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html_tag","S'",1,None,None,None),
  ('html_tag -> OPEN SRC ALT args END','html_tag',5,'p_html_tag','parser.py',6),
  ('args -> ID','args',1,'p_args','parser.py',11),
  ('args -> args ID','args',2,'p_args_multiple','parser.py',15),
]
